# Generated by Django 5.1.3 on 2024-12-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='ph_values',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='rainfall',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='crop_name',
            field=models.CharField(default='Rice', max_length=100),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='ec_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='soil_type',
            field=models.CharField(default='Loamy Soil', max_length=100),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='k_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='n_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='p_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='temperature',
            field=models.FloatField(default=25.0),
        ),
    ]
