# Generated by Django 5.1.3 on 2024-12-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userhistory_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='crop_name',
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='ec_value',
            field=models.FloatField(help_text='Electrical conductivity of the soil'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='k_value',
            field=models.FloatField(help_text='Potassium value in soil'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='n_value',
            field=models.FloatField(help_text='Nitrogen value in soil'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='p_value',
            field=models.FloatField(help_text='Phosphorous value in soil'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='soil_type',
            field=models.CharField(choices=[('loamy soil', 'loamy soil'), ('clayey soil - loamy soil', 'clayey soil - loamy soil'), ('well-drained - loamy soil', 'well-drained - loamy soil'), ('sandy clay', 'sandy clay'), ('sandy loam - silt loam', 'sandy loam - silt loam')], default='loamy soil', max_length=100),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='temperature',
            field=models.FloatField(help_text='Temperature in degrees Celsius'),
        ),
    ]
